### ISSUE TITLE
Community Review response from CTA WAVE

### ISSUE THREAD

**Issue by technogeek00** [Dash-Industry-Forum/Content-Steering#13]
The CTA WAVE DASH-HLS Interoperability group has reviewed the DASH content steering proposal and strongly supports its movement forward to further bring feature interoperability to the specifications. As part of its review, the following have been identified as specification inconsistencies and potential implementation question points that may need addressing. We submit them here for your consideration, bolded text in behavior columns highlight differences:

| Functionality | HLS Content Steering Behavior | DASH Content Steering Behavior | Recommendation |
|----|----|----|----|
| Server Query Time Requirements | After Start | After Start, **Optional Force before start with `ContentSteering@queryBeforeStart`** | Keep as is, potentially propose to HLS |
| Local Server Proxying | Not Supported | **`ContentSteering@proxyServerURL`** | Question: Why can this not be achieved with application logic since it must be aware of the proxy anyways? Application level handling will let proxying work within HLS as well as DASH |
| Feature Effect Radius | All variants / renditions pointed at by Multivariant Playlist | **All Periods with at least one `BaseURL` where the `@serviceLocation` matches a location in the steering manifest** | Question: How are periods that were matching and no longer matched after an update handled, seems to conflict with location remove behavior (see further down) |
| Unrecognized Key Handling | **Not Specified** | Client should ignore | Keep as is, potentially propose to HLS |
| Unrecognized Version Handling | Client should refuse | Client should refuse **after consuming `TTL` and `RELOAD-URI` values** | Ensure requirement of expected parsed keys never change across version or refuse parse and require default TTL in element |
| Steering Server HTTP 410 Response | Never request again, may use existing known responses | **Not Specified** | Match HLS Behavior |
| Steering Server HTTP 429 Response | Respect Retry-After if present | **Not Specified** | Match HLS Behavior |
| Reload TTL Signal | `TTL` key (required) | `TTL` key (**optional**) | Make required to ensure TTL exists if parse ever fails |
| Default TTL | 300 seconds (**only in case of no previous response**) | 300 seconds | Keep as is |
| Location Priorities | `PATHWAY-PRIORITY` key (required, array) | `SERVICE-LOCATION-PRIORITY` key (**optional**, array, **default false**) | Question(s): What does default "false" imply? Why is array not required, does not make sense without it |
| Location Cloning | `PATHWAY-CLONES` key (optional, array) | **Not Supported** | No benefit of supporting in DASH, recommend adding text around Location change across MPD updates as the best path |
| General Behavior | Switch to highest location in list that has not been penalized by client | Switch to highest location in list and **within active playout area** that has not been penalized by client | Keep as is, difference is due to Multivariant vs Period structure |
| Location Removed | Switch to next available location if one exists | Switch to next available location if one exists, **otherwise fail playback (?)** | Behavior conflicts with requirement to only apply steering manifest to matching Periods. Period can become no longer matching with removal, but that wouldn't have terminated playback if it had started not matching. Suggest stronger definition of Period alignment by moving steering node to Period. |
| Location penalty duration | Client determined time | **Time equal to last steering manifest TTL** | Keep as is, but make expectation soft |

Should any follow-ups or clarifications be desired we are always happy to re-engage.

Thanks,
DASH-HLS Interoperability Group

**Comment by dsilhavy** [comment]
Minutes from the DASH-IF Live Call on 2022-09-23:

#### Server Query Time Requirements
* HLS probably not going to accept it
* Add a "warning" to the DASH spec that this is not compliant with HLS

#### Local Server Proxying
* External system needs to know about local system because it adds the localhost steering server
* Blacklisting period is equal to TTL
* Should provide a diagram, use case description to highlight the different behavior
* Daniel, Thomas: Discuss this with 5G-MAG 

#### Feature Effect Radius
* Related to "Location Removed"
* SGAI: Periods resolved by component that steering server is not aware of?
  * Third-party ad distribution
* What if steering server defines service location priority A,B but manifest contains only C,D?
  * If none of the options from the steering are available just play the content or stop playback?
  * Should we add an additional attribute that defines the behavior to the specification?
    * failIfNoMatch, default: false, also applies to defaultServiceLocation
      * Is there an operator who would use that?
      * Not add this at this point, no usage identified
    * Will: Modify spec to change no match behavior.
* Add information to which period steering applies?
* Move <ContentSteering> element to period?
  * SGAI response could define a dedicated <ContentSteering> element for each period
  * <ContentSteering> element in period overwrites <ContentSteering> element on MPD level
* Multiple <ContentSteering> elements on MPD level and define which one to use on <Period> level
* When ads are defined usually doing CDN decision as part of the ad decision process
  * Are people really steering ads dynamically? Is that realistic?
* Steering of ads is possible with a single steering server
  * https://github.com/Dash-Industry-Forum/Content-Steering/issues/9
* **Outcome: Use the solution depicted in https://github.com/Dash-Industry-Forum/Content-Steering/issues/9**
* Do we need to allow multiple service locations in `@defaultServiceLocation`?
  * One is enough

#### Unrecognized key handling
* Unknown keys in JSON response from server -> Ignore, standard behavior

#### Unrecognized Version Handling
* Will: Change spec: Ignore response completely if no version matching

#### Steering Server HTTP 410 response
* Use cached/last response and stop steering timer
* The HyperText Transfer Protocol (HTTP) 410 Gone client error response code indicates that access to the target resource is no longer available at the origin server and that this condition is likely to be permanent
* Daniel: Implement this change in dash.js

#### Steering Server HTTP 429 response
* Overwrite ttl value and use 429 Retry-After value if present
* Daniel: Implement this change

#### Reload TTL Signal
* Will: Make ttl required in spec

#### Default TTL
* Stays 300, needs to be defined for cases in which response fails for the first time
* Otherwise, reuse last value

#### Location priorities
* Will: Change spec
  * Default to empty array
  * Add spec language that if multiple matches for serviceLocation the player can choose which one to use

#### Location Cloning
* Keep as is

#### General behavior
* No actions
#### Location Removed
* See above (Feature Effect Radius)

**Comment by will** [comment]
> @will: Modify spec to change no match behavior.
> @will: Make ttl required in spec
> @will: Change spec

Ah Jeeze I'm real sorry, but it'll take me a long time to get ramped up on this project, I've never heard about it before. And I have my day job too which has a bunch of things they expect me to do, or eventually probably they'd fire me. Can you find someone else to do these thigns?

**Comment by dsilhavy** [comment]
> > @will: Modify spec to change no match behavior.
> > @will: Make ttl required in spec
> > @will: Change spec
> 
> Ah Jeeze I'm real sorry, but it'll take me a long time to get ramped up on this project, I've never heard about it before. And I have my day job too which has a bunch of things they expect me to do, or eventually probably they'd fire me. Can you find someone else to do these thigns?

Sorry for the inconvenience my bad, copy&pasted the minutes from a different tool and did not remove the tags.

**Comment by technogeek00** [comment]
@will absolute gold. Sorry internal system @'ing didn't transfer well.

Should all be @wilaw

**Comment by haudiobe** [comment]
2022/10/07

- ok to remove the `ContentSteering@proxyServerURL` for content steering. In case a service wants to make use of the feature, it would remove the remote contentsteering element and point to the local server. The local server would contact the remote server and take into account the steering information when creating the response on the local server.
- other discussion will continue @wilaw will implement in updated spec

**Comment by wilaw** [comment]
All requested changes have been made to the post-community-review draft 0.9.5

One item that we never achieved consensus on is whether the ContentSteering@defaultServiceLocation attribute can hold multiple serviceLocations. The use case would be a manifest with multiple Location elements and BaseURL elements, all having serviceLocation descriptors. Additionally, there could be a first ad period with its own baseURLs which would need to be evaluated before the buffer was full and the steering server was requested. The multiple serviceLocations could be stored in a comma separated list as shown below:

`<ContentSteering defaultServiceLocation="loc2,ad1,primary2"> https://steeringservice.com/app/instance1234</ContentSteering>`

**Comment by haudiobe** [comment]
AHG 2022/12/13:
- Accepted https://github.com/Dash-Industry-Forum/Content-Steering/issues/13#issuecomment-1344875085 
- to be published for community review 2
