### ISSUE TITLE
Compatibility with HLS Steering Manifests

### ISSUE THREAD

**Issue by glenng1215gh** [Dash-Industry-Forum/Content-Steering#5]
It looks like we are so close to using the same steering manifest format as HLS Steering, but we've decided not to go all the way. Why not use "PATHWAY-PRIORITY" instead of "SERVICE-LOCATION-PRIORITY", as both are simply logical names for a pathway.

I see the note just above section 6.2 about pathway cloning not being applicable to DASH. What is the method for a steering server to introduce a new CDN (one not declared in the original MPD) after playback has started?

**Comment by wilaw** [comment]
Hi Glenn

When I first wrote the spec draft, it actually started out using exactly the same format as HLS steering, just as you suggest. In fact, the DASH clients would masquerade as HLS clients and the steering server would be unable to tell the difference between the two. This was how it was planned to work until May 22, after which the HLS spec was updated to add in a whole new cloning section. This complicated the spec with rules for deriving new pathways from prior pathways. Cloning is needed in HLS because the HLS player only loads the primary playlist once. This behavior is not needed in DASH because (to answer your second question) we can introduce a new service-location (pathway) at any manifest update. We could have made cloning work with DASH too and were about to do this work, but then we stopped to ask ourselves a bigger question - is this just the first step of many in which features are unilaterally introduced into the HLS spec without consideration of their impact on DASH? The answer to this is yes. Apple (quite rightfully) author content steering for use with their devices and their streaming format. DASH compatibility is not in their scope. Hence it is not prudent for DASH to define a behavior which is based on a specification over which they have no control or input. Therefore at our face-to-face meeting in June we decided to make DASH content steering independent-of, but still compatible with, HLS content steering. What does "compatible with" mean? It means everyone trying to steer both HLS and DASH clients (which is most large distributors) are going to find a fundamentally similar construct of timed requests to a steering server that responds with a JSON payload giving a prioritized list of resources.  But each format can then add specific enhancements - such as cloning for HLS and proxyServerURL for DASH.  The switch from  "PATHWAY-PRIORITY" to "SERVICE-LOCATION-PRIORITY" was intentional, to indicate during debugging that this was a response intended for a DASH player. Similarly, DASH players now identify themselves by using _DASH_ query args instead of _HLS_. I've spoken with two companies looking at building cross-format steering servers. Both like the separation of syntax and feature-set for DASH, while retaining the common base of interoperability.

**Comment by glenng1215gh** [comment]
thanks for the all the background Will. as you pointed out. the Apple HLS universe is quite inwardly focused and not terribly concerned with interoperability.

While DASH does have the advantage over HLS they mid-stream manifest updates can add new pathways, I do rather like the consistency of the HLS approach that gives the steering server control to not only drive CDN switches, but to also add new CDNs mid-stream. this provides a nice separation of concerns between manifest-generator and steering server.

would it be reasonable to allow a DASH steering server to add a new service location without the need to update the MPD?

**Comment by wilaw** [comment]
`" this provides a nice separation of concerns between manifest-generator and steering server."` - but actually it doesn't separate them at all, in fact it mixes them. If a steering server can introduce new service locations, now we have two sources of truth of where content can be accessed - one is the manifest generator (CMS) and the other is the steering server. I can envisage examples where this breaks down, or at least requires great coordination to ensure that the two sources do not diverge. In the real world, content sources are not ephemeral things. They take months of business negotiations, contracts and careful planning. What is the use case of a distributor who starts a live event and then adds a new CDN mid-way through that they _didn't know about at the beginning_?

However this is just my opinion. If you feel there is a strong use case for the steering server introducing new BaseURL elements, then please describe it and also mock up what it might look like.

**Comment by glenng1215gh** [comment]
you're probably right, and i do like the simplicity of the DASH steering approach as proposed. While it may be useful for the steering server to add CDNs, the HLS pathway cloning is kind of ugly ;-)
